### ISSUE TITLE
Move event_slot_id selection to /events/register page

### ISSUE THREAD

**Issue by thompson2091** [midohiofoodbank/freshtrak-client#101]
When a Foodbank shares a link to a particuar service event, they are linking the users to the /events/register page for that particular event.  We need to move the event_slot_id selection from the /event/list page over to the /events/register page so that a user linked directly to the /events/register page can properly select their event_slot_id.

<img width="935" alt="Screen Shot 2020-08-13 at 9 32 09 AM" src="https://user-images.githubusercontent.com/64417502/90140630-0638f000-dd48-11ea-8ffd-238d42ee5852.png">

**Comment by maheshkurma** [comment]
working on it.

**Comment by davidpickering** [comment]
Closed by #108
