### ISSUE TITLE
Address Validation Service during Pre-Registration

### ISSUE THREAD

**Issue by davidpickering** [midohiofoodbank/freshtrak-client#11]
**Customer Story**: I am a customer looking for food. I have successfully used the Pantry Finder experience with my zipcode to find a distribution I would like to attend. I am now proceeding through the pre-registration process and as I enter my address & zip code I would like it to autocomplete.

**Food Bank Story**: I am a food bank staffer, and after someone completes their registration, I have to import and match them to our existing data. Having a cleaned up, standardized, and well formatted address helps my systems to make matches automatically, and if manual intervention is needed I am able to work with the data more efficiently.

Service providers:
MOF has a free enterprise grade account with a company called SmartyStreets. This company has built a number of APIs and tools that interact with USPS data to provide address validation.
- Here is a link to their [API documentation](https://smartystreets.com/products/apis/us-street-api).
- They also have a variety of  [SDKs developed.](https://smartystreets.com/docs/sdk) . Including a [javaScript SDK](https://smartystreets.com/docs/sdk/javascript).

If there is an alternative provider that is easier to implement/better on certain dimensions. We are open to alternative suggestions. Please provide an alternative proposal, along with a cost estimate for 1M monthly lookups.

**Comment by davidpickering** [comment]
I think we all are familiar with this concept, but here is an example for reference:
![image](https://user-images.githubusercontent.com/11682225/80618604-99584f00-8a11-11ea-9809-d3463c16d893.png)

**Comment by Akshaysanthosh** [comment]
Hey thanks for providing this info. We have done our initial research on smartystreets and tested it with mock data. So far it looks good, we will further look into the autocomplete feature using provided credentials.

**Comment by davidpickering** [comment]
Closed by #43
