### ISSUE TITLE
Security Vulnerability: jquery

### ISSUE THREAD

**Issue by nvengal** [midohiofoodbank/freshtrak-client#12]
https://github.com/midohiofoodbank/freshtrak-client/network/alert/src/Assets/js/jquery.min.js/jquery/open

Remediation
Upgrade jquery to version 3.5.0 or later.

Always verify the validity and compatibility of suggestions with your codebase.

Details
GHSA-jpcq-cgw6-v4j6
moderate severity
Vulnerable versions: >= 1.0.3, < 3.5.0
Patched version: 3.5.0
Impact
Passing HTML containing <option> elements from untrusted sources - even after sanitizing it - to one of jQuery's DOM manipulation methods (i.e. .html(), .append(), and others) may execute untrusted code.

Patches
This problem is patched in jQuery 3.5.0.

Workarounds
To workaround this issue without upgrading, use DOMPurify with its SAFE_FOR_JQUERY option to sanitize the HTML string before passing it to a jQuery method.

References
https://jquery.com/upgrade-guide/3.5/

For more information
If you have any questions or comments about this advisory:

Open an issue in the jQuery repo
Email us at security@jquery.com
GHSA-gxr4-xjj5-5px2
moderate severity
Vulnerable versions: >= 1.2, < 3.5.0
Patched version: 3.5.0
Impact
Passing HTML from untrusted sources - even after sanitizing it - to one of jQuery's DOM manipulation methods (i.e. .html(), .append(), and others) may execute untrusted code.

Patches
This problem is patched in jQuery 3.5.0.

Workarounds
To workaround the issue without upgrading, adding the following to your code:

jQuery.htmlPrefilter = function( html ) {
	return html;
};
You need to use at least jQuery 1.12/2.2 or newer to be able to apply this workaround.

References
https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/
https://jquery.com/upgrade-guide/3.5/

For more information
If you have any questions or comments about this advisory:

Open an issue in the jQuery repo
Email us at security@jquery.com

**Comment by nvengal** [comment]
The security vulnerability looks to have been resolved.

However, I'm leaving this issue open to determine if we can remove the jquery script. Do we need jquery in this project? It doesn't look like it's actually being used, but I don't have enough react experience to be confident in that. Also, I expect dependencies to be managed by yarn/npm and find it weird that this minified file is sitting directly in the repo- https://github.com/midohiofoodbank/freshtrak-client/blob/master/src/Assets/js/jquery.min.js.

Thoughts, @seanlawrenz @maheshkurma @andyschofield ?

**Comment by ashikvarma11** [comment]
We can safely remove the jquery file and scripts.js file in the same folder as they were used to toggle the size of Header component in the earlier stages of development. The logic is rewritten inside the component itself.

**Comment by maheshkurma** [comment]
@nvengal yes we can remove this file, the toggle is working fine in header component without script.js, actually it is using bootstrap toggle.

**Comment by davidpickering** [comment]
A small pull request to remove [this file](https://github.com/midohiofoodbank/freshtrak-client/blob/master/src/Assets/js/jquery.min.js) should resolve this issue (Thanks @maheshkurma )

**Comment by seanlawrenz** [comment]
@nvengal @davidpickering @maheshkurma 

I believe this is a dependent of bootstrap and react bootstrap. As long as there are no regressions it should be okay to remove. However we should definitely disclose that jQuery is removed for the sake of another developer outside this loop adds a component or functionality that comes boxed with bootstrap.

**Comment by davidpickering** [comment]
@seanlawrenz Thanks for the heads up. 

Now that you mention it I recall that Bootstrap is dependent on jQuery: https://getbootstrap.com/docs/4.5/getting-started/introduction/#js

Does that mean we have to leave Jquery on the site? I don't have a problem with this, feel free to educate me further.

**Comment by seanlawrenz** [comment]
I'd say leave it. It'll get tree shaken out if it is not used. Ultimately it'll be removed with bootstrap 5 if we want to update.

**Comment by davidpickering** [comment]
Closed due to being unsure of current Jquery usage, and existing Bootstrap 4 dependency.
