### ISSUE TITLE
Registration - MVP(scaled back) - Modify Existing Front End

### ISSUE THREAD

**Issue by davidpickering** [midohiofoodbank/freshtrak-client#13]
Minimalist registration flow:
1. Login
freshtrak-registration-api on  initial-api via :gem: v2.6.5
```
❯ curl -XPOST localhost:4444/api/guest_authentications
{
  "id": 2,
  "user_id": 2,
  "token": "vKwdYwzWRGYjrbgrEy7XrfiF",
  "expires_at": "2020-05-15T14:06:23.000Z",
  "created_at": "2020-05-01T14:06:23.699Z",
  "updated_at": "2020-05-01T14:06:23.699Z"
}
```
All other requests require an auth header with the access token from this step.
2. Update User
freshtrak-registration-api on  initial-api via :gem: v2.6.5
```
❯ curl -XPOST --header 'Authorization: Bearer vKwdYwzWRGYjrbgrEy7XrfiF' 'localhost:4444/api/user' --data '{"user":{"first_name":"Lester","last_name":"Bellowfield","zip_code":"43201","adults_in_household":2}}'
{
  "id": 2,
  "first_name": "Lester",
  "last_name": "Bellowfield",
  "zip_code": "43201",
  "adults_in_household": 2,
  "identification_code": "W3R-B2S",
  "user_type": "guest",
  "created_at": "2020-05-01T14:06:23.697Z",
  "updated_at": "2020-05-01T14:12:33.014Z",
  "middle_name": null,
  "suffix": null,
  "date_of_birth": null,
  "gender": null,
  "phone": null,
  "permission_to_text": null,
  "email": null,
  "permission_to_email": null,
  "address_line_1": null,
  "address_line_2": null,
  "city": null,
  "state": null,
  "license_plate": null,
  "seniors_in_household": null,
  "children_in_household": null
}
```
Generates a persistent identification_code that can be used to id the user.
3. Create reservation (Requires a valid event_date_id from the pantry-finder db)
freshtrak-registration-api on  initial-api via :gem: v2.6.5

```
❯ curl -XPOST --header 'Authorization: Bearer vKwdYwzWRGYjrbgrEy7XrfiF' localhost:4444/api/reservations --data '{"reservation":{"event_date_id":117}}'
{
  "id": 4,
  "user_id": 2,
  "event_date_id": 117,
  "created_at": "2020-05-01T14:18:43.854Z",
  "updated_at": "2020-05-01T14:18:43.854Z"
}
```

Checks to make sure that the user is not already registered for this event. Reaches out the pantry-finder-api to ensure that the event_date still has capacity. (edited)

**Comment by davidpickering** [comment]
@seanlawrenz FYI. I am going to post some more details about the shift in Slack, but the short version is @nvengal is pretty close to merging a PR to introduce an endpoint that the front end can send data to in order to write a registration to a single wide table.

**Comment by seanlawrenz** [comment]
@davidpickering Can I assume that the update user data will be the same for registering for the first time?

**Comment by nvengal** [comment]
> Can I assume that the update user data will be the same for registering for the first time?

Seems like a safe assumption to me.

**Comment by nvengal** [comment]
WIP backend pr for reference: https://github.com/midohiofoodbank/freshtrak-registration-api/pull/4

**Comment by davidpickering** [comment]
Lots of PRs contributed to this. 
@nvengal @maheshkurma @seanlawrenz Thank you all and everyone else!
