### ISSUE TITLE
New Google Tag Manager Events for Modal Open and Guest Login

### ISSUE THREAD

**Issue by thompson2091** [midohiofoodbank/freshtrak-client#130]
This is a request for new Google Tag Manager events to be fired when:

1. the login modal opens on the event details (registration) page
2. the user selects **Continue as Guest** from modal

![Screen Shot 2020-09-15 at 12 57 13 PM](https://user-images.githubusercontent.com/64417502/93241185-0109ff00-f753-11ea-8ddc-986dd2ac820c.png)

There is already an implementation of a Google Tag Manager event within RegistrationContainer.js.  The site currently uses the following code to fire our **reservation** event:

`
TagManager.dataLayer({
  dataLayer: {
    event: "reservation"
  }
})
`

I have created two new events within Google Tag Manager that we will want to fire on their respective events:

a) on Modal Open

`
TagManager.dataLayer({
  dataLayer: {
    event: "modal-open"
  }
})
`

b) on Continue as Guest

`
TagManager.dataLayer({
  dataLayer: {
    event: "guest-login"
  }
})
`

**Comment by davidpickering** [comment]
Closed by PR #132
