### ISSUE TITLE
Add Facebook Login Event to Google Tag Manager

### ISSUE THREAD

**Issue by thompson2091** [midohiofoodbank/freshtrak-client#133]
We need to add a new event that gets fired in Google Tag Manager anytime a user logins with a Facebook Account.

We need the following code applied as soon as the user clicks Login with Facebook:

`
TagManager.dataLayer({
           dataLayer: {
                       event: “facebook-login”
           }
})
`

<img width="701" alt="Screen Shot 2020-09-16 at 8 22 13 AM" src="https://user-images.githubusercontent.com/64417502/93346543-19852280-f802-11ea-9d4d-a02184cddec9.png">

Similar work was done in PR #130 for Continue as Guest

**Comment by davidpickering** [comment]
Confirmed functionality in the beta
![image](https://user-images.githubusercontent.com/11682225/94607304-bb2c5b00-0269-11eb-85db-d97929276ee7.png)
