### ISSUE TITLE
Register Button Not Working when User Token Exists

### ISSUE THREAD

**Issue by thompson2091** [midohiofoodbank/freshtrak-client#142]
When clicking the Register Now button on the events/details page you are supposed to get the login modal to fire.  However, if you already have a userToken, the modal is not firing.

Here is an example of expected behavior:
![Screen Shot 2020-09-23 at 5 41 24 PM](https://user-images.githubusercontent.com/64417502/94072710-369e9000-fdc4-11ea-8db5-07e5e64c4b67.png)

Furthermore, I do see the guest-login Google Tag Manager event firing.  This leads me to believe that the page is attempting to login as a guest user, but is not redirecting to the registration form properly.

Here is where I can see the guest-login event firing upon clicking the Register Now button:

![Screen Shot 2020-09-23 at 5 42 08 PM](https://user-images.githubusercontent.com/64417502/94072953-a44abc00-fdc4-11ea-8381-059745dbe927.png)

![Screen Shot 2020-09-23 at 5 49 35 PM](https://user-images.githubusercontent.com/64417502/94073277-33f06a80-fdc5-11ea-9b28-05fc86121d09.png)

**Comment by davidpickering** [comment]
Setup: Have a token, go to click 'Register Now'
![image](https://user-images.githubusercontent.com/11682225/94607670-34c44900-026a-11eb-8b57-d3fdc6e4e97f.png)

Click "Register Now" - success - get the form
![image](https://user-images.githubusercontent.com/11682225/94607699-3f7ede00-026a-11eb-9eba-35580c9ec082.png)
