### ISSUE TITLE
Show error message in UI if  user has already registered for a specific event 

### ISSUE THREAD

**Issue by maheshkurma** [midohiofoodbank/freshtrak-client#154]
If user registers for same event - response from back end will => user_id: ["has already registered for this event"]

Handle this error and show message when user try's to register for same event multiple times.

**Comment by maheshkurma** [comment]
PR is merged into master and deployed to beta.

**Comment by sarath-yerra** [comment]
This Is fixed and Deployed to Production on 10/21
