### ISSUE TITLE
Pantry Finder - Introduce Address-Based Search Method

### ISSUE THREAD

**Issue by davidpickering** [midohiofoodbank/freshtrak-client#16]
Would like to introduce an address-based search method. 
- Would like a Zip Code - or - autocomplete address + zip code option for the UI. 
- If someone uses the autocomplete address option, submit the zip code and their address' lat/long to the API, and get very specific distance sorting.
- This work can be done in advance of the distance changes in pantry-finder-api.

Example of Address Validation service:
![image](https://user-images.githubusercontent.com/11682225/81368047-d16c2b80-90bc-11ea-80e8-5ec5162c25ee.png)

Service providers:
MOF has a free enterprise grade account with a company called SmartyStreets. This company has built a number of APIs and tools that interact with USPS data to provide address validation.
- Here is a link to their [API documentation](https://smartystreets.com/products/apis/us-street-api).
- They also have a variety of  [SDKs developed.](https://smartystreets.com/docs/sdk) . Including a [javaScript SDK](https://smartystreets.com/docs/sdk/javascript).

If there is an alternative provider that is easier to implement/better on certain dimensions. We are open to alternative suggestions. Please provide an alternative proposal, along with a cost estimate for 1M monthly lookups.

**Comment by Akshaysanthosh** [comment]
We have done a bit more R&D on the Address Validation Service and it is our understanding that the Smartystreet US Autocomplete Pro is the service that suits us the most. The Basic Autocomplete service from Smartystreet will only return an unverified address and we have to use one more API to validate it. The  Autocomplete Pro will return the validated suggestion along with Latitude longitude parameters as the response.

( If we want to proceed with  Autocomplete Pro  we need to purchase that specific service , currently it is not available with  the provided  Smartystreet Account ) 

This is an example of Smartstreet US Autocomplete Pro feature returning verified addresses with latitude and longitude 

![Screenshot 2020-05-26 at 12 58 45 PM](https://user-images.githubusercontent.com/16001487/82879898-3cda4800-9f5b-11ea-84b9-1ac17f0faa1f.png)

**Comment by Akshaysanthosh** [comment]
We need clarification regarding the field which we plan to implement this auto-complete functionality ,is this just the Street Address field in the family registration page ? or also in any other new field as well ?

**Comment by ashikvarma11** [comment]
As discussed with Mark on the call, we have proceeded with Google Places API instead of Smartystreets for address autocompletion. We have used `react-places-autocomplete` library for ease and are getting the address suggestion like this as of now. 

![Screenshot from 2020-05-28 14-22-03](https://user-images.githubusercontent.com/24647741/83138718-d8f58200-a108-11ea-82c9-37733a1dba8f.png)


Does the autocompletion part goes with Street Address field in Pre-registration form or is there any other place where we should implement this.

**Comment by davidpickering** [comment]
@ashikvarma11, great work on that feature. 

As for where to plug it in, long term we want to include it in the pre-registration form, but there are a lot of moving parts on that feature and we can delay that update for a little bit. Instead, we will implement it first as a part of the search process. 

Here is a mockup of what we want:
![image](https://user-images.githubusercontent.com/11682225/83205712-54f9c500-a11d-11ea-9918-ba257aa78b3f.png)

What it should do:
- The customer comes to the page and enters their zip code
- Once the zip code is entered, the street address input should appear to the top/left of the zip code input. This is an optional feature, and at this point the customer could click 'Search for Resources' and get results just with a zip code.

![image](https://user-images.githubusercontent.com/11682225/83208659-3ba84700-a124-11ea-8c5d-1d48b4c815c0.png)


- The customer may choose to enter their address, and click 'Search for Resources' and get results customized to their address. 
![image](https://user-images.githubusercontent.com/11682225/83208939-07815600-a125-11ea-8c3f-97ad33bff859.png)


- Generate a call  with additional parameters to the call like this: https://pantry-finder-api.beta.freshtrak.com/api/agencies?zip_code=43123&lat=40.146000&long=-83.075890'
- The API will then customize the estimated distance in the returned JSON object based on the  parameters provided.

Background:
- The PR that introduced this feature was in [pantry-finder/PR3](https://github.com/midohiofoodbank/freshtrak-pantry-finder-api/pull/3) and there is some additional documentation about this feature there.
- The feature was written by @PhilNorman2 
- This features allows the search results to be customized to the address of the customer, not just to the center of the zip code.

**Comment by ashikvarma11** [comment]
@davidpickering  Thanks for the detailed info. Appreciate it.

I have worked on the integration and managed to get things up and running like this as of now. 

![Screenshot from 2020-05-29 19-20-39](https://user-images.githubusercontent.com/24647741/83267241-8b991380-a1e1-11ea-941d-144b7aebf078.png)

![screenshot-localhost_3000-2020 05 29-19_13_52](https://user-images.githubusercontent.com/24647741/83267586-0eba6980-a1e2-11ea-93a7-d00cd1f62d10.png)


But, I see that we have 3 unclosed issues #15, #10 and #9 which are dependant on this feature. Could you clarify a little bit more about the status of those and when they are merged to master?
  
I've also changed the logic on the form inside SearchComponent to react-hook-forms to remove custom form handling functions.
 
I'm confused as to whether I should drop a PR now or after those are merged and updated.

**Comment by davidpickering** [comment]
@ashikvarma11 
> But, I see that we have 3 unclosed issues #15, #10 and #9 which are dependant on this feature. Could you clarify a little bit more about the status of those and when they are merged to master?

I closed #15, and would still consider #10 and #9 open to-do items, but I think we need API work done in Ruby to move forward on those.
