### ISSUE TITLE
Show Event Details on Confirmation Page

### ISSUE THREAD

**Issue by thompson2091** [midohiofoodbank/freshtrak-client#167]
We would like to show the Event Details on the confirmation page (i.e. when a user successfully makes a reservation).

Currently, the confirmation page looks like this (contains the Foodbank name):

![Screen Shot 2020-10-06 at 5 56 42 PM](https://user-images.githubusercontent.com/64417502/95586856-44345680-0a0f-11eb-8590-e565685c09ae.png)

We would like to also include the details of the event they just registered for - the same data that is on /events/details (event name, type, address, phone & start/end time)

![Screen Shot 2020-10-09 at 9 11 10 AM](https://user-images.githubusercontent.com/64417502/95587005-8067b700-0a0f-11eb-8e67-da174a7a649a.png)

The event details can go between the Foodbank Name and the Your Information sections on the confirmation page:

![Screen Shot 2020-10-06 at 5 56 42 PM](https://user-images.githubusercontent.com/64417502/95587365-f5d38780-0a0f-11eb-9679-8e43e2a8c15e.png)

**Comment by sarath-yerra** [comment]
Sure Matt
