### ISSUE TITLE
Foodbank website URL text wrapping outside the card

### ISSUE THREAD

**Issue by pantrytrak-core** [midohiofoodbank/freshtrak-client#169]
The text for the URL is extending outside the edges of the Foodbank card. 

![image](https://user-images.githubusercontent.com/6410110/95751451-a0e07d00-0c6c-11eb-9775-16b0a8e93579.png)

**Comment by sarath-yerra** [comment]
<img width="1257" alt="Screen Shot 2020-10-12 at 4 00 24 PM" src="https://user-images.githubusercontent.com/69260104/95785623-17e53800-0ca4-11eb-9337-497b4169618d.png">

**Comment by maheshkurma** [comment]
Fixed this Issue, deployed in beta.
we will close this issue once it is tested in Prod.

**Comment by sarath-yerra** [comment]
This Is fixed and Merged to Master and Deployed to Production on 10/21
