### ISSUE TITLE
Pantry Finder - Foodbanks Section - Pull foodbank_logo from DB and use it for the image

### ISSUE THREAD

**Issue by davidpickering** [midohiofoodbank/freshtrak-client#18]
Dependent on [pantry-finder-api/PR5](https://github.com/midohiofoodbank/freshtrak-pantry-finder-api/pull/5) - Ready to work!
******************************
Currently, all of the foodbanks are displaying the Mid-Ohio Food Collective logo

e.g. a cleveland zip code should show the Greater Cleveland Food Bank logo.
![foodbank logo](https://user-images.githubusercontent.com/11682225/79938416-8c909580-842a-11ea-802f-bebc8b22f9ff.png)

- E.g. 43123 shows the MOF logo correctly.

![foodbank - singular](https://user-images.githubusercontent.com/11682225/79938291-328fd000-842a-11ea-88a5-aced87287c96.png)

If there are multiple agencies service the zip code, they each will get their own logo
- If number of foodbanks > 1 (Food Bank**s**) - plural e.g. 45320
![image](https://user-images.githubusercontent.com/11682225/79938184-e3499f80-8429-11ea-948e-3d1a24c95d37.png)

E.g. Shared Harvest - [Logo](https://secure.feedingamerica.org/images_logos/FoodBankLogo_129_275w.jpg)
E.g. The Foodbank, INC. [Logo](https://secure.feedingamerica.org/images_logos/FoodBankLogo_121_275w.jpg)

Added the logo field in the foodbanks api for the UI to consume per:

midohiofoodbank/freshtrak-public#78

Also added the id field for referential integrity. Here is an example request/response:

http://localhost:8888/api/foodbanks?zip_code=14903

`
{
    "foodbanks": [
        {
            "id": 28,
            "address": "388 Upper Oakwood Ave",
            "city": "Elmira",
            "state": "NY",
            "zip": "14903",
            "phone": "",
            "name": "Food Bank of the Southern Tier",
            "nickname": "Food Bank of the Southern Tier",
            "logo": "nyfbst.jpg",
            "display_url": "https://www.foodbankst.org/",
            "fb_agency_locator_url": "",
            "fb_url": "https://www.foodbankst.org/",
            "fb_fano_url": "https://www.feedingamerica.org/find-your-local-foodbank"
        }
    ]
}
`

**Comment by seanlawrenz** [comment]
Couple of questions. 
Is there a default logo for returns that have no logo, and what is the url of the logos?

Currently the api returns `"logo": "nybst.jpg"`, that will not render as that asset is not in the project.

**Comment by davidpickering** [comment]
Hey Sean, good spot on the ` "logo": "nybst.jpg",`. This is one downside of the testing environment we have set up. I updated that particular logo to [this](https://secure.feedingamerica.org/images_logos/FoodBankLogo_28_275w.jpg) ~1 week ago.

![Uploading image.png…]()

As for a default logo, I would say the Feeding America [logo](https://www.feedingamerica.org/themes/custom/ts_feeding_america/images/sprite-logo2018.png) would be a good default option. Based on the current data, a user can't make this happen, but you are right, we should contain for it.
