### ISSUE TITLE
Strip Non-Alphanumeric Characters from All Form Fields

### ISSUE THREAD

**Issue by thompson2091** [midohiofoodbank/freshtrak-client#187]
We recently had an incident where a user input a non-alphanumeric character into the first_name field which caused issues on the PantryTrak side.  In order to not have that happen, we want to strip any non-alphanumeric characters from all form fields before they are inserted into the database.  I will also be adding the same type of logic on the PantryTrak side for redundancy.

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/64417502/97008309-a3ff2700-1510-11eb-93e8-dd973d9b1411.png)

**Comment by sarath-yerra** [comment]
1.Fixed issues related non-alphanumeric characters
2.Also Stripping spaces if there is a space before FN,MN,LN
3.Saving into DB After Stripping.
4.Showing on Confirm Page After Stripping.

**Comment by maheshkurma** [comment]
@thompson2091 @sarath-yerra 
question: Do we also need to strip non-alphanumeric characters for `address_line_1` field ?
becasue it aceepts alphanumeric characters now as below

<img width="837" alt="Screen Shot 2020-10-27 at 2 52 50 PM" src="https://user-images.githubusercontent.com/20909776/97348699-e6a06680-1864-11eb-8efe-a71791c0e0b9.png">

**Comment by thompson2091** [comment]
Yes, we should strip for all fields.  I just implemented the same thing onto the PantryTrak end and here is what it looks like:

For all fields (excluding id, created_at and updated_at), we are removing any character that IS NOT included in the list below:
- A-Z (i.e. capital A through capital Z .. For example, A, B, C, D, etc..)
- a-z (i.e. lowercase a through lowercase z .. For example: e, f, g, h, etc..)
- 0-9
- &mdash; (i.e. the hyphen/dash symbol)
- @ (i.e. the at symbol, this is used in email addresses)
- . (i.e. the period, which could be used in email and/or addresses)
- ' (i.e. the apostrophe, which Sarath has already taken care of)
- ` (i.e. the tick symbol, which I believe Sarath has already addressed)
