### ISSUE TITLE
New Income level and Assistance information page

### ISSUE THREAD

**Issue by Akshaysanthosh** [midohiofoodbank/freshtrak-client#30]
Hey found this new page in Figma. I just wanted to check whether you guys have already started working on it or we should start.  I am opening this as an issue because this page is new and unrelated. Feel free to close it, if this page is not necessary right now or someone has already started working on it. @davidpickering  @nvengal 

![Screenshot 2020-06-02 at 8 43 23 AM](https://user-images.githubusercontent.com/16001487/83520816-f016e400-a4fb-11ea-9efc-703978f9e90c.png)

**Comment by davidpickering** [comment]
Thanks @Akshaysanthosh , I'll double check, but I think we are pausing on this feature. There are some updated wireframes, and we are trying to make some architecture decisions about DB-driven vs. Hard coded, and how to record the responses.

**Comment by davidpickering** [comment]
Yeah, we have some updated wireframes, but need to make some architecture decisions about how to support the feature throughout the full stack. @Akshaysanthosh  I have four issues (yet to be written) I'll poin you and @ashikvarma11 at.
