### ISSUE TITLE
Address Lookup on Pre-Register feature

### ISSUE THREAD

**Issue by davidpickering** [midohiofoodbank/freshtrak-client#38]
Much like the work done in freshtrak-client/PR29 we want to apply address auto completion to the FreshTrak Pre-Registration processes.

![image](https://user-images.githubusercontent.com/11682225/84554234-fb7cc300-ace4-11ea-88ba-9c16f5fdbe9b.png)

A few notes:

- Google API Key - does not need to be secret, let's include in the source code. Yes, it can leak out - but it is also accessible through some clever work with the front end. Our site is served up as static files through cloudfront and the key is also accessible through some work in the front end.
- The Pro of this is that we save some time trying to deploy this feature out. If we have to replace the key frequently (more than once per month) we'll consider a new approach to better protect this key.
- Long-Term - if this is a problem we will move to a proxy process to abstract the API calls to Google's API behind some Lambdas.
-Let's also do the refactor of the Pantry Finder front end to just use an established API key:
![image](https://user-images.githubusercontent.com/11682225/84554357-7645de00-ace5-11ea-836e-693151b9dcda.png)

**Comment by ashikvarma11** [comment]
@davidpickering Thank you for the info. We have pushed the code to `FT-16.0-Registration-AddressSearch` branch. Since #29 also uses the same dependencies on the same files, we'll create a PR once we fix on which feature goes to master first.

**Comment by davidpickering** [comment]
Closed by PR43 #43
