### ISSUE TITLE
Registration Form - AutoFill Address - Fills into single input

### ISSUE THREAD

**Issue by davidpickering** [midohiofoodbank/freshtrak-client#51]
There is an issue with the Auto Fill address in the Pre-Registration form. The information is filled into a single input, it should be broken apart into the appropriate inputs

Desired Behavior:
- User begins entering their address in address 1 input
- google API returns suggestions
- user chooses a suggestion, and clicks on it
- The appropriate components of the address are returned into the separate inputs on the registration form.

Wrong (current behavior):
![image](https://user-images.githubusercontent.com/11682225/86048558-b5cb3480-ba1e-11ea-9c4b-25f28c4b8c85.png)

Correct:
![image](https://user-images.githubusercontent.com/11682225/86048524-a9df7280-ba1e-11ea-9277-3333df29d115.png)

File: https://github.com/midohiofoodbank/freshtrak-client/blob/a6f2be046538aafee9eaaa44ed7df7ec2736dfdd/src/Modules/Family/AddressComponent.js

**Comment by ashikvarma11** [comment]
#58 Fixes are made.

**Comment by davidpickering** [comment]
Pretty sure PR #58 will resolve this. Just needs to get reviewed and tested.
