### ISSUE TITLE
FreshTrak "Stay Up to Date"

### ISSUE THREAD

**Issue by aportermidohiofoodbank** [midohiofoodbank/freshtrak-client#59]
On a call today Marketing suggested we add "Coming soon" to the "Stay Up to Date" section which says "Make a FreshTrak account to stay up to date on local food access events." 
![freshtrak stay up to date](https://user-images.githubusercontent.com/68286187/87434628-b33d1300-c5b8-11ea-9f1f-a1573d311657.png)

**Comment by davidpickering** [comment]
![image](https://user-images.githubusercontent.com/11682225/87705997-c42e8580-c76c-11ea-9f44-45fcf2c42a31.png)
