### ISSUE TITLE
Menu Icon on Mobile 

### ISSUE THREAD

**Issue by Hey-Steve-Dev** [midohiofoodbank/freshtrak-client#60]
There is a hamburger menu icon that appears on the mobile version of the site but it doesn't function. No menu pops up as a result of a touch event. This issue is present on Safari and Chrome Mobile.

**Comment by davidpickering** [comment]
There is a menu that links to some pages. The pages are turned off right now because we are in Beta. Let's also temporarily turn off this hamburger menu (The Three line icon) icon.

![image](https://user-images.githubusercontent.com/11682225/87706114-fd66f580-c76c-11ea-9579-c6fa9babe433.png)

**Comment by Hey-Steve-Dev** [comment]
Just fyi, it looks like there are two button objects one with a class navbar-toggler.collapsed that is possibly blocking the working button with the class name of navbar-toggler. If you resize the browser window to just before the threshold of switching to mobile view, you can see both buttons display at the same time. Note that when you do this, one of the buttons will work, but when you size down the screen more, the second buttons appear to go overtop the first (working) button. Good luck!
![FreshTrak Nav](https://user-images.githubusercontent.com/50382058/87797329-871fcd00-c818-11ea-8d4f-526bab843ad0.PNG)
