### ISSUE TITLE
Links on page not working correctly. 

### ISSUE THREAD

**Issue by Hey-Steve-Dev** [midohiofoodbank/freshtrak-client#61]
The links on the bottom of the page do not work correctly when selected. The page view changes, but the view is not indexed to the top of the page, instead it displays the bottom of the new page. This issue is present on mobile and desktop.

**Comment by davidpickering** [comment]
![image](https://user-images.githubusercontent.com/11682225/87706325-520a7080-c76d-11ea-9dc6-7ee6739c8d5b.png)

FreshTrak About:
![image](https://user-images.githubusercontent.com/11682225/87706357-5cc50580-c76d-11ea-8b44-b0dcdd477053.png)

Working with FreshTrak:
![image](https://user-images.githubusercontent.com/11682225/87706396-70706c00-c76d-11ea-93d5-e238d6fb8e01.png)

@Hey-Steve-Dev looking at this, makes sense. Clicking on "Working with FreshTrak" does take you to the right page, but not to the top of the content. 👍
