### ISSUE TITLE
Search result length 

### ISSUE THREAD

**Issue by Hey-Steve-Dev** [midohiofoodbank/freshtrak-client#62]
The search for some zip codes produces results that are very lengthy on mobile. It is hard to differentiate between the dates of the search results and you have to scroll past a large number of panels to get to dates in the future. Suggested fix, deliver search results in chunks followed by a "view more" or other lazy load functionality, or have a filter by date function.

**Comment by davidpickering** [comment]
Agreed, for a large metropolitan county (Franklin, Cuyahoga, etc...) there is probably 'too much' information. For many of our rural counties, there will not be many opportunities shown. 

With ~3 weeks under our belts it looks like many foodbanks will follow this progression with their implementation:
1. Publishing and linking to single service dates + RSVPs?
2. Publishing and linking to all service dates for a single agency + RSVPs?
3. Publishing many agencies and having people use the general zip code searching tool to find relevant distributions + RSVPs?

The search results are meant to apply to use case 3. Our theory is that when people use the search results they are looking for food now, or browsing for the near future (~1 week). Usage of the site will prove or disprove that long-term. Until we have more data, we are not making any editorial decisions about what content is being shown by default to customers when they use the search function. We are exploring some user-filtering of the results; for more information, we have an issue in the [pantry-finder-api](https://github.com/midohiofoodbank/freshtrak-pantry-finder-api/issues/7).
