### ISSUE TITLE
App does not work in IE

### ISSUE THREAD

**Issue by seanlawrenz** [midohiofoodbank/freshtrak-client#68]
We can decide if we want to support it, but the app will require [some polyfills](https://github.com/facebook/create-react-app/blob/master/packages/react-app-polyfill/README.md) to support the old broswers.

**Comment by davidpickering** [comment]
Thanks looking into that @seanlawrenz . I would say in general we want to support the widest breadth of users and technology out there. My only caveat would be if that support begins limiting features we can use or if we spend lots of time tuning use for 1% of users.

Could you share some rough stats on which version of IE our app has issues with? E.g. Users on a windows VISTA desktop with IE6 wont be able to use the site vs. User with a brand new computer using Microsoft Edge can't use the site.

**Comment by seanlawrenz** [comment]
@davidpickering I'd limit support to IE 11. It would increase the bundle size but might be worth it for that group of users.

**Comment by davidpickering** [comment]
Closed because of EOL on IE11
