### ISSUE TITLE
Fix Needed for Expired Authentications

### ISSUE THREAD

**Issue by davidpickering** [midohiofoodbank/freshtrak-client#78]
User Feedback:
Hello! We are getting reports of an infinite buffering circle from folks who are trying to register for tomorrow's pantry.. just thought to pass the info along!

![image](https://user-images.githubusercontent.com/11682225/88241841-5b0dad00-cc59-11ea-8c52-492e6dceb736.png)

Diagnosis:
- Good News: We dug into this with our dev team and figured it out.
- Bad news: **If someone first used FreshTrak over 14 days ago, but did not complete a registration, then returned to the site to make a reservations they would have encountered this issue. This looks like a limited population of ~160 users.**
- Short-term Fix: We identified a fix, and implemented a temporary fix in our test environment, and then in our production environment. In short, we gave everyone more "time" in their guest authentication.
- Long-Term Fix: We identified a more long-term programmatic solution and have it in the development pipeline. 

Temporary Fix Notes
[Fix Notes.txt](https://github.com/midohiofoodbank/freshtrak-client/files/4963307/Fix.Notes.txt)

Long Term Fix Instructions:

- When someone arrives on the https://beta.freshtrak.com/events/register/[id] page, check their user_token
- if the token has expired, remove the token from their local storage ([example here](https://github.com/midohiofoodbank/freshtrak-client/pull/36/files))
- Issue the user a new auth token ([example here](https://github.com/midohiofoodbank/freshtrak-client/blob/8aea1902a9dd16daa7d2270e4052754e9a3cadd5/src/Modules/Family/RegistrationContainer.js#L35))

**Secondary issue** - It appears the logic of unsetting someone's auth token after registration was accidentally removed in a PR. 

- The PR that should still be reflected but is not - [PR36](https://github.com/midohiofoodbank/freshtrak-client/pull/36/files)
- This [File](https://github.com/midohiofoodbank/freshtrak-client/blob/master/src/Modules/Family/RegistrationConfirmComponent.js) should reflect the remove.token process, but does not. We should restore the functionality from PR36.

**Comment by davidpickering** [comment]
Before Registering:
![image](https://user-images.githubusercontent.com/11682225/88242854-85ad3500-cc5c-11ea-843e-c0de360c18f6.png)

About to click Register:
![image](https://user-images.githubusercontent.com/11682225/88242915-b42b1000-cc5c-11ea-9145-aadc73e5bdab.png)

Button is disabled preventing duplicate clicks! Nice! 
![image](https://user-images.githubusercontent.com/11682225/88242931-c147ff00-cc5c-11ea-835d-61304934e2c0.png)

Token is still present. This is definitely an issue:
![image](https://user-images.githubusercontent.com/11682225/88242958-d58bfc00-cc5c-11ea-869f-37dd257b0f0f.png)

Please restore lost code originally committed in #36 

@nvengal - As part of my ongoing education, how do we find out where we lost that bit of code?

**Comment by maheshkurma** [comment]
code committed in #36 was removed in PR#40.

**Comment by davidpickering** [comment]
> 
> 
> code committed in #36 was removed in PR#40.

Thanks Mahesh! You'll have to show me how you figured that out.
