### ISSUE TITLE
Change source of Service Category in pantry finder API results

### ISSUE THREAD

**Issue by PhilNorman2** [midohiofoodbank/freshtrak-client#84]
Currently the Service Category in the display (circled in picture below) is pulled from the "service:" field in the event JSON object in the pantry finder API results (agencies endpoint).   In the future it should be pulled from the "service_category_name: " field in the service_category object (child of event) as shown in https://github.com/midohiofoodbank/freshtrak-pantry-finder-api/pull/45. 

<img width="303" alt="Screen Shot 2020-07-31 at 6 02 35 PM" src="https://user-images.githubusercontent.com/31697968/89080905-289a3900-d358-11ea-95fd-e092b2ee994c.png">

**Comment by seanlawrenz** [comment]
I think this is done.
